# Generated by Django 3.0.2 on 2020-01-27 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examMaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=11, validators=[users.models.is_phone])),
                ('national_code', models.CharField(max_length=10, validators=[users.models.is_national_code])),
                ('field_study', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, choices=[('U', 'Undergraduate'), ('M', 'Masters Degree'), ('P', 'PHD')], max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', related_query_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=2, max_digits=2)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examMaker.Exam')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marks', related_query_name='mark', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
