# Generated by Django 3.0 on 2020-03-24 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('about', models.TextField(blank=True, max_length=2000, verbose_name='about')),
                ('num_chasers', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('admins', models.ManyToManyField(related_name='pages', to=settings.AUTH_USER_MODEL)),
                ('chasers', models.ManyToManyField(blank=True, related_name='chased_pages', to=settings.AUTH_USER_MODEL)),
                ('special_chasers', models.ManyToManyField(blank=True, related_name='special_chased_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-num_chasers',),
            },
        ),
    ]
