# Generated by Django 3.0 on 2020-03-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='admins',
            new_name='owner',
        ),
    ]
