# Generated by Django 3.0 on 2020-03-25 12:47

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200324_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='special_chasers',
            new_name='special_users',
        ),
        migrations.AddField(
            model_name='store',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[store.validators.price_validator]),
        ),
    ]
