# Generated by Django 3.0 on 2020-03-25 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_auto_20200325_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='special_users',
            field=models.ManyToManyField(blank=True, related_name='special_subscriptions', related_query_name='special_subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
