# Generated by Django 3.0 on 2020-03-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200325_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='owner',
            new_name='owners',
        ),
    ]
