# Generated by Django 3.0 on 2020-03-24 21:05

import django.core.validators
from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200324_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=product.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-rate_p', 'create_date')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='product',
            name='medias',
            field=models.ManyToManyField(related_name='products', related_query_name='products', to='product.MediaFile'),
        ),
    ]
