# Generated by Django 3.0 on 2020-03-25 12:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import product.models
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_auto_20200325_1247'),
        ('product', '0003_auto_20200324_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='special',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[product.validators.price_validator]),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='special_users',
            field=models.ManyToManyField(related_name='bought_medias', related_query_name='bought_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[product.validators.price_validator]),
        ),
        migrations.AddField(
            model_name='product',
            name='special_users',
            field=models.ManyToManyField(related_name='bought_products', related_query_name='bought_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(blank=True, upload_to=product.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'mp3', 'mp4', 'mkv']), product.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='medias',
            field=models.ManyToManyField(related_name='products', to='product.MediaFile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rated_by',
            field=models.ManyToManyField(blank=True, related_name='rated_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.Store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(related_name='products', to='product.Subcategory'),
        ),
    ]
