# Generated by Django 3.0 on 2020-03-25 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_auto_20200325_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='special_users',
            field=models.ManyToManyField(blank=True, related_name='bought_medias', related_query_name='bought_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='special_users',
            field=models.ManyToManyField(blank=True, related_name='bought_products', related_query_name='bought_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
