# Generated by Django 3.0 on 2020-03-28 12:35

import django.core.validators
from django.db import migrations, models
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200328_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'mp3', 'mp4', 'mkv']), product.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(blank=True, upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'mp3', 'mp4', 'mkv']), product.validators.validate_file_size]),
        ),
    ]
